# Generated by Django 5.2 on 2023-11-15 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('chatting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')],
                default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='message',
            name='delivery_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='last_delivery_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
