# Generated by Django 5.2 on 2025-05-04 09:36

import django.utils.timezone
from django.db import migrations, models

import chatting.models


class Migration(migrations.Migration):
    dependencies = [
        ('chatting', '0002_message_delivery_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_attachment',
            field=models.FileField(blank=True, null=True, upload_to=chatting.models.message_file_path),
        ),
        migrations.AddField(
            model_name='message',
            name='file_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file_type',
            field=models.CharField(blank=True,
                                   choices=[('image', 'Image'), ('document', 'Document'), ('audio', 'Audio'),
                                            ('video', 'Video'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(
                choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed')],
                db_index=True, default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='is_online',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='userstatus',
            name='last_active',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
