# Generated by Django 5.2 on 2025-04-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the user', null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
