# Generated by Django 5.2 on 2025-05-08 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', 'add_performance_indices'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_date_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='appointment_user_instructor_idx',
        ),
        migrations.RemoveIndex(
            model_name='comment',
            name='comment_post_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='like',
            name='like_post_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_recipient_idx',
        ),
        migrations.RemoveIndex(
            model_name='notification',
            name='notification_type_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_created_idx',
        ),
        migrations.RemoveIndex(
            model_name='post',
            name='post_user_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_name_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_code_idx',
        ),
        migrations.RemoveIndex(
            model_name='subject',
            name='subject_active_idx',
        ),
        migrations.RemoveIndex(
            model_name='subjectenrollment',
            name='enrollment_student_subject_idx',
        ),
    ]
