# Generated by Django 5.2 on 2025-04-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='posts/documents/'),
        ),
    ]
