# Generated by Django 5.2 on 2025-04-30 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_question_profilecertification_profileeducation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_randomized',
            field=models.BooleanField(default=False, help_text='Randomize question order for each attempt'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='total_marks',
            field=models.PositiveIntegerField(default=0, help_text='Total possible marks for this quiz'),
        ),
    ]
