# Generated by Django 5.2 on 2025-04-30 05:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_question_remove_education_user_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='quiz',
            name='home_quiz_creator_c34a82_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='home_quiz_status_9c44d4_idx',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='total_marks',
            new_name='passing_score',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='marks',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_type',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_randomized',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='shuffle_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='status',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='visibility',
        ),
        migrations.AddField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes'),
        ),
    ]
